sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "10"
  - "12"
matrix:
  include:
    - node_js: "7"
      env: TEST_SUITE=standard
    - node_js: "7"
      env: TEST_SUITE=coverage
env:
  - TEST_SUITE=test
script: npm run-script $TEST_SUITE
